### ISSUE TITLE
Unable to initialize Aepp object

### ISSUE THREAD

**Issue by Jkat** [waellet/waellet#127]
**Describe the bug**
Unable to initialize Aepp object, getting an error: `ReferenceError: Aepp is not defined`
Seems to work on certain websites, but not others.
For example it doesn't work on `https://addons.mozilla.org/en-US/firefox/addon/waellet/?src=search` but works on `https://hack.bg/`

**To Reproduce**
1. Install extension
2. Go to developer console
3. Try to use `Aepp.request.connect()`

**Expected behavior**
Waellet pops up a request

**Desktop**
 - MacOS 10.14
 - Firefox
 - 69.0

**Comment by mradkov** [comment]
This should be resolved by using AEX2 for means of communication between Aepp<>Waellet.
