### ISSUE TITLE
Feedback: UI overlapping buttons

### ISSUE THREAD

**Issue by mradkov** [waellet/waellet#143]
![](https://www.crowdholding.com/assets/ckeditor/dr.martinberger/2019/08/31/misaligned_buttons.png)

![](https://www.crowdholding.com/assets/ckeditor/dr.martinberger/2019/08/31/sizing_problem.png)

**Comment by vmangelovv** [comment]
I tried Chrome, Firefox, Opera and i do not see this overlapping. Everything looks good
