### ISSUE TITLE
Bug: Argon2-asm missing

### ISSUE THREAD

**Issue by mradkov** [waellet/waellet#171]
Local build is missing the `argon2-asm.min.js` and throwing error later in the browser which is not allowing user to proceed with Account view.

**Comment by petbaik** [comment]
> Local build is missing the `argon2-asm.min.js` and throwing error later in the browser which is not allowing user to proceed with Account view.

This happen after update of the version of argon2-browser package. Local build working with version 1.5.2. Current version is 1.11.1 (https://github.com/waellet/waellet/commit/0b85e1abf6cf66af8e86aa945eb5b7c33052a465#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33)
