### ISSUE TITLE
Use webcrypto instead argon2

### ISSUE THREAD

**Issue by mradkov** [waellet/waellet#219]
Is it feasible to use webcrypto (provided by the browser itself) for state encryption instead of argon2. 

This is a step forward speeding up the extension performance in general.

One possible drawback(?) - since Chrome won't allow access to webcrypto for pages served via HTTP unless it's at `localhost` this may affect some non-TLS non-localhost gateways.

Web Crypto API status:
- Chrome restricts access to webcrypto since version 60.
- Firefox is planning to Require [SecureContext] for Web Crypto as well.

Rf. #214 https://github.com/w3c/webcrypto/issues/28

**Comment by mradkov** [comment]
https://www.w3.org/TR/WebCryptoAPI/

**Comment by mradkov** [comment]
The `argon2` was also removed from the sdk. Ref. https://github.com/aeternity/aepp-sdk-js/pull/782

**Comment by petbaik** [comment]
> The `argon2` was also removed from the sdk. Ref. [aeternity/aepp-sdk-js#782](https://github.com/aeternity/aepp-sdk-js/pull/782)

Is this mean that we can use keystore from sdk without migrating to webcrypto

**Comment by mradkov** [comment]
> > The `argon2` was also removed from the sdk. Ref. [aeternity/aepp-sdk-js#782](https://github.com/aeternity/aepp-sdk-js/pull/782)
> 
> Is this mean we can use keystore from sdk without migrating to webcrypto

We can try and see what the benefits will be. The overall goal is for the extension to be more performant, and speed it up.
