### ISSUE TITLE
Language switcher is not working correctly

### ISSUE THREAD

**Issue by mradkov** [waellet/waellet#222]
Only `en` and `ch` works.

**Comment by vmangelovv** [comment]
That's why we do not have translations for the others langs

**Comment by mradkov** [comment]
You can use [these automated ones](https://docs.google.com/spreadsheets/d/1DJTdm0ofVl0Omlz4hxfW1QS4CZh0Dl3Vc6BXcGOxnqY/edit#gid=0) until we have a proper translation for a particular language.
