### ISSUE TITLE
Login view shown multiple times on almost every action.

### ISSUE THREAD

**Issue by kraikov** [waellet/waellet#223]
**Describe the bug**
Whenever I want to call a static function of a contract, the waellet login view appears and asks me to enter my password. Once I do that, it asks me again and again, until I refresh and relog in to the waellet.

This happens also when calling non static functions, but more seldom.

**To Reproduce**
1. Call static function of any contract

**Expected behavior**
Once I enter my password, I should remain logged until I leave the browser?

**Desktop (please complete the following information):**
 - OS: [ubuntu]
 - Browser [brave]
 - Version [0.2.25]

**Comment by kraikov** [comment]
Actually I don't think the Waellet popup should be invoked at all when calling a static function. It's confusing that way.

**Comment by mradkov** [comment]
Yes we will remove that, as the static call does not require any user interaction nor signing.

Thanks for the issue reporting!

**Comment by mradkov** [comment]
After investigation @petbaik found what was causing the issue.

This will be resolved in the next release.
