### ISSUE TITLE
Fungible token shows multiple times in the list

### ISSUE THREAD

**Issue by mradkov** [waellet/waellet#265]
**Describe the bug**
Adding the same fungible token via `Utilities > Fungible tokens > Add token` results in having it multiple times on the dropdown list.

**To Reproduce**
1. Go to `Utilities > Fungible tokens > Add token`
2. Search for `Yair` or any other token.
3. Click add token

**Expected behavior**
If user happens to add the same token (with the **same address**) that is already on the dropdown list of his waellet extension should not display it multiple times.

**Screenshots**
![d5466940-7d59-4fba-8edd-c6a5dc242376](https://user-images.githubusercontent.com/13139371/73074399-390dba80-3ec2-11ea-9554-b22e9ab49993.png)
<img width="362" alt="Screenshot 2020-01-24 at 15 51 12" src="https://user-images.githubusercontent.com/13139371/73074401-3c08ab00-3ec2-11ea-8ab6-0018da7fdb08.png">
<img width="362" alt="Screenshot 2020-01-24 at 15 51 20" src="https://user-images.githubusercontent.com/13139371/73074403-3d39d800-3ec2-11ea-93e5-12d1f571be97.png">
<img width="358" alt="Screenshot 2020-01-24 at 15 51 30" src="https://user-images.githubusercontent.com/13139371/73074405-3f039b80-3ec2-11ea-9da4-bc48bcfb7505.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Brave
 - Version: 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

**Comment by petbaik** [comment]
I was not able to reproduce this problem.
