### ISSUE TITLE
Connection status not set to DISCONNECTED when Aepp closed

### ISSUE THREAD

**Issue by petbaik** [waellet/waellet#272]
There is problem with client disconnect when closing Aepp, which leads to error when changing accounts and networks from Wallet. The error is
![image](https://user-images.githubusercontent.com/8629465/73162733-27612880-40f7-11ea-8d1a-29275d5cfb09.png)
because port (client) is closed but it's status is still **CONNECTED**: 
I think the problem is comming from incorrect client instance passed in `onDisconnect` method in `RpcWallet`. 
![image](https://user-images.githubusercontent.com/8629465/73164066-d999ef80-40f9-11ea-8c59-51e4ddfc3690.png)

- When calling `disconnectWallet` (https://github.com/aeternity/aepp-sdk-js/blob/develop/es/utils/aepp-wallet-communication/rpc/aepp-rpc.js#L131) from Aepp the client status is set to disconnected and in `onDisconnect` method the `client` param is instance of `RpcClient  ` (https://github.com/aeternity/aepp-sdk-js/blob/develop/es/utils/aepp-wallet-communication/rpc/rpc-clients.js#L108)
![image](https://user-images.githubusercontent.com/8629465/73163546-e407b980-40f8-11ea-9630-94bdebd02700.png)

 - When Aepp is disconnected from window or tab close the client status is not set to disconnected and in `onDisconnect` method the `client` param is instance of `BrowserRuntimeConnection` (https://github.com/aeternity/aepp-sdk-js/blob/develop/es/utils/aepp-wallet-communication/connection/browser-runtime.js#L102)
![image](https://user-images.githubusercontent.com/8629465/73163568-f2ee6c00-40f8-11ea-9576-55ba529c2afd.png)

**Comment by mradkov** [comment]
@petbaik was this fixed with https://github.com/aeternity/aepp-sdk-js/pull/880?

**Comment by petbaik** [comment]
> @petbaik was this fixed with [aeternity/aepp-sdk-js#880](https://github.com/aeternity/aepp-sdk-js/pull/880)?

yes

**Comment by mradkov** [comment]
Then this should be resolved when we merge #292 ?

**Comment by mradkov** [comment]
Resolved in #292
