### ISSUE TITLE
AEX-2 communication problem in Firefox

### ISSUE THREAD

**Issue by petbaik** [waellet/waellet#273]
There is problem in communication between Aepp and extension in Firefox. 

The first error is thrown in the extension: 
![image](https://user-images.githubusercontent.com/8629465/73248309-5fca3a80-41bb-11ea-91d2-76e2297d4eac.png) (https://github.com/aeternity/aepp-sdk-js/blob/develop/es/utils/aepp-wallet-communication/connection/browser-runtime.js#L57)

After removing this locally another exception is thrown in Aepp and no connection is established
![image](https://user-images.githubusercontent.com/8629465/73248426-a0c24f00-41bb-11ea-994a-5f3afef5db4a.png)

**Comment by nduchak** [comment]
Fixed in https://github.com/aeternity/aepp-sdk-js/pull/882

**Comment by nduchak** [comment]
Guys, can you please test it and if it's ok I will start the release process of `7.0.0`

**Comment by mradkov** [comment]
Works now!

> Guys, can you please test it and if it's ok I will start the release process of `7.0.0`
