### ISSUE TITLE
Waellet contract call fail address and balance incorrect 

### ISSUE THREAD

**Issue by intnick** [waellet/waellet#295]
Hi guys,
I keep getting “Incorrect address” when trying to make a contract call, and also insufficient balance.
I use windows with both Chrome and Firefox, same error. installed the newest version of Waellet, created an account, logged in into the account. Using testnet.
I tried directly in the developer console as well, calling window.Aepp.request.contractCall(NFT_CONTRACT_SOURCE, NFT_CONTRACT_ADDRESS, ‘transfer_from’ , [publicKey, receiverAeternityAddress, tokenId]);
the variable do have correct values

The address is correct and I do have funds on the account

![9b4292c9cfc9e85efa0792f077e801296b8494e7 1](https://user-images.githubusercontent.com/1571030/75145031-7f8c4a00-56f8-11ea-8531-627d502a6d4a.png)

**Comment by petbaik** [comment]
Hey @intnick can you try this
```javascript
window.Aepp
.request
.contractCall({
  source:NFT_CONTRACT_SOURCE,
  address: NFT_CONTRACT_ADDRESS,
  method: 'transfer_from',
  params: [publicKey, receiverAeternityAddress, tokenId],
})
```

**Comment by intnick** [comment]
Great, that's it in regards to calling the contract function.
One small thing remaining is that I still get the balance on my account of 0, and a flash message insufficient balance. 

![image](https://user-images.githubusercontent.com/1571030/75196694-cdd33480-575c-11ea-9bc4-22ec15086979.png)


But the message is only there for a sec and it goes away so I can call the contract, even thought the balance is stated to be 0
![image](https://user-images.githubusercontent.com/1571030/75196721-dd527d80-575c-11ea-82d4-6ce4a71675d0.png)

But it's not
![image](https://user-images.githubusercontent.com/1571030/75196848-1559c080-575d-11ea-9248-afbfa2cb8bce.png)

**Comment by petbaik** [comment]
Hey @intnick.
This balance here is the amount passed along with the transaction, not the account balance
![image](https://user-images.githubusercontent.com/8629465/75223829-fa646c00-57af-11ea-938f-49a15f7aa354.png)
For instance if we want to pass **0.1AE** with the transaction we add `options` param
```js
window.Aepp
.request
.contractCall({
  source:NFT_CONTRACT_SOURCE,
  address: NFT_CONTRACT_ADDRESS,
  method: 'transfer_from',
  params: [publicKey, receiverAeternityAddress, tokenId],
  options:{amount:100000000000000000}
})
```
![image](https://user-images.githubusercontent.com/8629465/75223892-149e4a00-57b0-11ea-93bf-3ce2dae3a944.png)

About the flash message `Insufficient balance`, I provided a fix here: https://github.com/waellet/waellet/pull/296
