### ISSUE TITLE
Can't detect wallet using AEX-2

### ISSUE THREAD

**Issue by kraikov** [waellet/waellet#314]
**Describe the bug**
The behavior of the Waellet extension is inconsistent when attempting to connect to it. First I tried to use the 0.5.1 release in Brave, but the wallet was not detected at all. Then I build the development branch and the wallet was detected and I was able to connect to Waellet. However after a few more attemps I was no longer able to connect.

```
const connectWallet = async () => {
    console.log('Looking for wallet');
    await Node({ url: NODE_URL, internalUrl: NODE_INTERNAL_URL }).then(
      async node => {
        await RpcAepp({
          name: 'JELLY SWAP',
          nodes: [{ name: 'mainnet', instance: node }],
          compilerUrl: COMPILER_URL
        }).then(async client => {
          const scanner = BrowserWindowMessageConnection({
            connectionInfo: { id: 'spy' }
          });

          await Detector({ connection: scanner }).then(detector => {
            console.log('DETECTOR: ', detector);
            detector.scan(async ({ wallets, newWallet }) => {
              if (!newWallet) return;
              detector.stopScan();
              const result = await client.connectToWallet(
                await newWallet.getConnection()
              );
              console.log(result);
              const res = await client.subscribeAddress('subscribe', 'current');
            });
          });
        });
      }
    );
  };`

```

**To Reproduce**
1. Try to connect to Waellet using the new AEX-2 standart.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 0.5.1

**Additional context**

**Comment by kraikov** [comment]
UPDATE: after restarting the browser, the waellet is detected and a connection is established. However, if I exit the application website and return on it without closing the browser I can't connect.

**Comment by petbaik** [comment]
> UPDATE: after restarting the browser, the waellet is detected and a connection is established. However, if I exit the application website and return on it without closing the browser I can't connect.

Is there any errors

**Comment by kraikov** [comment]
```
Uncaught Error: Attempting to use a disconnected port object
    at Object.shareWalletInfo (wallet-rpc.js:322)
    at eval (rpcWallet.js:541)
helpers.js:57 Receive invalid message Object

```

**Comment by petbaik** [comment]
> ```
> Uncaught Error: Attempting to use a disconnected port object
>     at Object.shareWalletInfo (wallet-rpc.js:322)
>     at eval (rpcWallet.js:541)
> helpers.js:57 Receive invalid message Object
> ```

What about the page running the script above ?

**Comment by kraikov** [comment]
No, only warnings about source-map.

```DevTools failed to parse SourceMap: chrome-extension://ibnejdfjmmkpcnlpebklmnkoeoihofec/dist/pageHook.js.map
```

**Comment by petbaik** [comment]
Is your wallet unlocked

**Comment by petbaik** [comment]
Interesting I run the script above and every time wallet is found. First time popup requesting connection is shown and every time I reload the page the connection is established.

**Comment by petbaik** [comment]
I will investigate what can cause connection problem in this case.

**Comment by kraikov** [comment]
So everytime the callback from detector.scan is invoked?

**Comment by petbaik** [comment]
> detector

yes

**Comment by petbaik** [comment]
> So everytime the callback from detector.scan is invoked?

Yes

**Comment by kraikov** [comment]
Not on my side.

**Comment by mradkov** [comment]
@kraikov Can you check if https://github.com/waellet/waellet/pull/315 resolves your issue?
