### ISSUE TITLE
Cannot add new custom token in waellet. 

### ISSUE THREAD

**Issue by tima-t** [waellet/waellet#319]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mradkov** [comment]
Thanks for reporting this! I was just able to reproduce this. We will fix it asap.

**Comment by tima-t** [comment]
I have opened the same issue with more details, so we can close this one.
