### ISSUE TITLE
Cannot add new custom token in waellet. 

### ISSUE THREAD

**Issue by tima-t** [waellet/waellet#320]
**Describe the bug**
I am using chrome and version 0.4.2 beta of the waellet.
1 When I open the extension and click on add new custom token
2 I put the contract address ct_pqfbS94uUpE8reSwgtaAy5odGi7cPRMAxbjMyEzpTGqwTWyn5
3 It finds the token symbol AES, 18 decimals and when I click add the extension freezes

I also believe that there is some problem with the decimals for the tokens, but I cannot be sure because I cannot add it. However, on the blurred background my balance looks like a very big number, when I have only a few tokens.

**Comment by mradkov** [comment]
Ref. #319

**Comment by mradkov** [comment]
Can you try with 0.5.2 (latest) and see if this is still present?

**Comment by mradkov** [comment]
I suspect this is related to the latest AEX9 interface changes. @petbaik is on it.

**Comment by tima-t** [comment]
I confirm that we have the same problem with v 0.5.2

**Comment by mradkov** [comment]
> I confirm that we have the same problem with v 0.5.2

Can you confirm its only for custom AEX9 tokens or balance in general?
