### ISSUE TITLE
I cannot send amount bigger than 1000 Ae tokens using waellet

### ISSUE THREAD

**Issue by tima-t** [waellet/waellet#321]
**Describe the bug**
I am using the latest version of waellet and chrome browser.

When I try to send some amounts that are higher than 1000 ae tokens - the waellet sends transaction, but it is only for 1 aetos. 

It should be some limitation or decimals problems when sending more than 1000 AE in one transaction

**Comment by mradkov** [comment]
> **Describe the bug**
> I am using the latest version of waellet and chrome browser.
> 
> When I try to send some amounts that are higher than 1000 ae tokens - the waellet sends transaction, but it is only for 1 aetos.
> 
> It should be some limitation or decimals problems when sending more than 1000 AE in one transaction

Can you please give the exact version tag which you are using as chrome store have still not approved 0.5.2 in the store and the "latest" one there is 0.4.2.

Please try with 0.5.2 and see if this is still present. (use FF or the gh-release)

**Comment by mradkov** [comment]
This is resolved in version > 0.5.0.
