### ISSUE TITLE
When I select some token e.g AES I do not see any transaction history on my account page

### ISSUE THREAD

**Issue by tima-t** [waellet/waellet#331]
When I click on tokens and select some token different from AE I cannot see my transaction history.

I think that the trasnaction history should be available and does not depend on the selected token.
I do not see the transaction history even for the selected token.

waellet version 0.5.4

**Comment by mradkov** [comment]
You don't see the tx history at all or just the `contractCall` is not listed there when you make a token transfer?

**Comment by tima-t** [comment]
Both. No history nor contractCall tx.
