### ISSUE TITLE
Cannot connect waellet to dApp using the sdk

### ISSUE THREAD

**Issue by tima-t** [waellet/waellet#333]
When we are trying to connect waellet extension to our app (app.jelly.market) it does not react.

Sometimes it is connected successfully, sometimes it is not.

Looks like the extension has inconsistent behavior and initialization problem.

We have strictly followed the integration docs.

It is happening on metamask version 0.5.4 beta and  firefox.

On chrome with the same version I have the following error

inject.js:1 Uncaught (in promise) Error: Extension context invalidated.

Do you have any suggestions or similar problems.

It could be some integrational issue, tho

**Comment by mradkov** [comment]
> It is happening on metamask version 0.5.4 beta and firefox.

By `metamask` you mean `waellet`, right :) 

> inject.js:1 Uncaught (in promise) Error: Extension context invalidated.

This usually indicates that something in the extension changed - either revoked access, or trying to invoke method of the waellet with previous connection. 

Can you provide us some code for reproducing this?

**Comment by mradkov** [comment]
Should be fixed by #349
