### ISSUE TITLE
Blank screen for some transactions triggered using AEX2 Wallet Connection

### ISSUE THREAD

**Issue by the-icarus** [waellet/waellet#352]
**Describe the bug**
When I use a AEX2 Wallet Connection to the waellet plugin I get blank screens for several transactions. Currently, I saw two transaction types where the issue occures:
- aensUpdate()
- aensClaim()

**To Reproduce**
1. Integrate the waellet on a page using AEX2 (similar to [Superhero UI](https://github.com/aeternity/superhero-ui/blob/develop/src/utils/walletSearch.js)
2. Trigger aensUpdate with the connected wallet sdk using a name you own, a pointer array, and the new nameTtl.
2.1 Alternative: or aensClaim (use the result object of the aensPreclaimTx)
3. The waellet popup will open with a blank page showing errors in console.

**Expected behavior**
The waellet popup should not be bank and display the prepared transaction with the options to reject or accept

**Desktop (please complete the following information):**
 - Browser Brave
 - Version v1.9.76
 - SDK Version 7.3.1

**Additional context**
I also checked some other transactions:
 - SpendTx
 - PreClaim
 - NameRevoke
which do not show a blank screen and can be confirmed/rejected in the waellet popup

**Comment by marc0olo** [comment]
@mradkov haven't checked that in Supehero yet but there it's possible to perform these actions right? at least the claim action I think. is that bug fixed there or how can that be possible?

**Comment by mradkov** [comment]
Yeah in superhero you can claim names and you can update them just fine, we recently did refactored the logic there.

Names in waellet are a bit outdated atm.
