### ISSUE TITLE
request.connect throwing an error

### ISSUE THREAD

**Issue by intnick** [waellet/waellet#359]
**Describe the bug**
I’m trying to do a contract call via Waellet. While prepping it with
window.Aepp.request.connect();
I get the error
Uncaught (in promise) TypeError: Cannot set property 'resolve' of undefined at inject.js:9

First I tried it in the new Edge where I also had superhero wallet and thought it was a clash between the two wallets (something similar mentioned Two "issues" with wallet connection to different wallets using the aepp-sdk-js 2). Then I removed superhero and it remains the same. I tried it in Chrome and still getting the same.

**To Reproduce**
1. Open Console
2. type const c = await window.Aepp.request.connect();
3. See error

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Edge Dev, Firefox...

**Comment by mradkov** [comment]
Thanks for reporting. We'll check it out

**Comment by mradkov** [comment]
Have you tried connecting to the wallet using the AEX-2 standard?  https://github.com/aeternity/AEXs/blob/master/AEXS/aex-2.md

You can find an example in the SDK here: https://github.com/aeternity/aepp-sdk-js/blob/6dd2e7390d570e238d28347e7b761b18495c4d18/examples/browser/vuejs/connect-two-ae/aepp/src/components/Home.vue#L300-L328

**Comment by intnick** [comment]
Hi Milen,
Yes, I did manage to get it up and running based on the Vue example. Took a while but managed :)

**Comment by mradkov** [comment]
> Hi Milen,
> Yes, I did manage to get it up and running based on the Vue example. Took a while but managed :)

Glad it worked out. As mentioned in the wiki section of waellet - the injected `Aepp` object will be deprecated, so the propper connection should be established via AEX2.

Closing the issue :)
