### ISSUE TITLE
Import wallet - views

### ISSUE THREAD

**Issue by mradkov** [waellet/waellet#52]
Ability to choose the import method:

- plain private key
- keystore.json [keystore format according to [aex-3](https://forum.aeternity.com/t/aex-3-secure-storage-format/3220/2)]
- seed phrase [Check base-aepp seed import view]

===

**Comment by petbaik** [comment]
Fixed in https://github.com/waellet/waellet/pull/69

**Comment by petbaik** [comment]
Improvements in pull https://github.com/waellet/waellet/pull/70
