### ISSUE TITLE
Sign/confirm modal view UI

### ISSUE THREAD

**Issue by mradkov** [waellet/waellet#63]
Notifications modal for confirming user actions

![image.png](https://images.zenhubusercontent.com/5cd013f2cdc0ba05ef4f1366/8a5b0d9e-bca0-4d00-af02-6eff55ad924a)

![image.png](https://images.zenhubusercontent.com/5cd013f2cdc0ba05ef4f1366/4e869026-59d0-4e28-822c-3724ef421640)

**Comment by petbaik** [comment]
Fixed in https://github.com/waellet/waellet/pull/82
