### ISSUE TITLE
Login button is "dead" after an incorrect password entry

### ISSUE THREAD

**Issue by prot-delux** [waellet/waellet#99]
So I am trying to login into the wallet with a pass. I did not get it right the first time, so I needed to enter the pass again. However, the second time I enter it, the “login” button is no longer doing anything. I edit my password, press login, but nothing happens.

**Comment by mradkov** [comment]
The problem was located - issue #81 is causing this, and it is already addressed.

**Comment by mradkov** [comment]
This should be fixed by fixing #81 in pull #98. New version with hot-fixes will be released this week.
